names(appended_dates_df)[1] <- "mosaic_id"
names(appended_dates_df)[2] <- "source_name"
names(appended_dates_df)[3] <- "ra"
names(appended_dates_df)[4] <- "e_ra"
names(appended_dates_df)[5] <- "dec"
names(appended_dates_df)[6] <- "e_dec"
names(appended_dates_df)[7] <- "peak_flux"
names(appended_dates_df)[8] <- "e_peak_flux"
names(appended_dates_df)[9] <- "total_flux"
names(appended_dates_df)[10] <- "e_total_flux"
names(appended_dates_df)[11] <- "maj"
names(appended_dates_df)[12] <- "e_maj"
names(appended_dates_df)[13] <- "min"
names(appended_dates_df)[14] <- "e_min"
names(appended_dates_df)[15] <- "dc_maj"
names(appended_dates_df)[16] <- "e_dc_maj"
names(appended_dates_df)[17] <- "dc_min"
names(appended_dates_df)[18] <- "e_dc_min"
names(appended_dates_df)[19] <- "pa"
names(appended_dates_df)[20] <- "e_pa"
names(appended_dates_df)[21] <- "dc_pa"
names(appended_dates_df)[22] <- "e_dc_pa"
names(appended_dates_df)[23] <- "lsl_rms"
names(appended_dates_df)[24] <- "s_code"
names(appended_dates_df)[25] <- "number_pointings"
names(appended_dates_df)[26] <- "masked_fraction"
names(appended_dates_df)[27] <- "source_centre_ra"
names(appended_dates_df)[28] <- "source_centre_dec"
names(appended_dates_df)[29] <- "source_coefficient"
names(appended_dates_df)[30] <- "source_date"





